# Generated by Django 3.1.1 on 2020-10-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Porcentaje',
            field=models.DecimalField(choices=[('0', '0'), ('16', '16')], decimal_places=2, default='0', max_digits=9, verbose_name='ivaPorcentaje'),
        ),
    ]
