# Generated by Django 3.1.1 on 2020-10-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20201006_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='iva',
            field=models.CharField(choices=[('0', '0'), ('16', '16')], default=0.0, max_length=10, verbose_name='Iva%'),
        ),
    ]
