# Generated by Django 3.1.1 on 2020-10-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_auto_20201006_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(max_length=10, unique=True, verbose_name='Zona'),
        ),
    ]
