# Generated by Django 3.1.1 on 2020-10-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20201012_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unidad',
            field=models.CharField(max_length=100, null=True, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='iva',
            field=models.CharField(max_length=10, verbose_name='Iva%'),
        ),
    ]
