# Generated by Django 3.1.1 on 2020-10-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_auto_20201012_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.CharField(max_length=100, verbose_name='Categoría'),
        ),
    ]
