# Generated by Django 3.1.1 on 2020-10-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_auto_20201026_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pui',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='PU+Iva'),
        ),
    ]
